#!/usr/bin/env python3
import os
import re
from datetime import datetime

# 1. Locate repo root & combined.rules
script_dir = os.path.dirname(os.path.abspath(__file__))
repo_root = os.path.abspath(os.path.join(script_dir, ".."))
rules_path = os.path.join(repo_root, "rules", "combined.rules")

# 2. Base config template
config_lines = [
    "%YAML 1.1",
    "---",
    f"# Generated by gen_suricata_config.py at {datetime.utcnow().isoformat()}Z",
    "vars:",
    "  address-groups:",
    '    HOME_NET: "[192.168.1.0/24]"',
    '    EXTERNAL_NET: "[8.8.8.8, 1.1.1.1]"',
    '    HTTP_SERVERS: "[192.168.1.10]"',
    '    DNS_SERVERS: "[192.168.1.53]"',
    '    SMTP_SERVERS: "[192.168.1.25]"',
    '    SQL_SERVERS: "[192.168.1.143]"',
    '    SHELLCODE_SERVERS: "[192.168.1.200]"',
    '    SIP_SERVERS: "[192.168.1.5060]"',
    '    AIM_SERVERS: "[192.168.1.4099]"'
]

# 3. Scan for all $*_PORTS variables in rules
port_pattern = re.compile(r"\$(\w+_PORTS)\b")
detected_vars = set()

if not os.path.exists(rules_path):
    print(f"❌ combined.rules not found at {rules_path}, skipping port var detection")
else:
    with open(rules_path, "r") as rules_file:
        for line in rules_file:
            for var in port_pattern.findall(line):
                detected_vars.add(var)

# 4. Log what we found
print(f"🔍 Detected port variables: {sorted(detected_vars)}")

# 5. Safe default mappings
default_ports = {
    "HTTP_PORTS":    "[80,443,8080,8000]",
    "DNS_PORTS":     "[53]",
    "SMTP_PORTS":    "[25,587]",
    "SQL_PORTS":     "[1433,3306]",
    "SHELLCODE_PORTS":"[10000]",
    "SIP_PORTS":     "[5060]",
    "AIM_PORTS":     "[4099]",
    "FTP_PORTS":     "[21]",
    "IRC_PORTS":     "[6667]",
    "TELNET_PORTS":  "[23]",
    "RDP_PORTS":     "[3389]"
}

# 6. Inject defaults for each detected var
for var in sorted(detected_vars):
    val = default_ports.get(var, "[1]")
    config_lines.append(f"    {var}: \"{val}\"")

# 7. Final stanzas
config_lines.append("default-rule-path: rules")
config_lines.append("default-log-dir: /tmp/suricata-logs")

# 8. Write out the YAML
output_path = "/tmp/suricata.yaml"
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, "w") as out:
    out.write("\n".join(config_lines) + "\n")

print(f"✔ Suricata config written to {output_path}")