#!/usr/bin/env python3
import os
import re
from datetime import datetime

# 1. Resolve paths
script_dir  = os.path.dirname(os.path.abspath(__file__))
repo_root   = os.path.abspath(os.path.join(script_dir, ".."))
rules_path  = os.path.join(repo_root, "rules", "combined.rules")
output_path = os.path.join(repo_root, "suricata.yaml")  # ✅ Write to repo root

print(f"🔍 Scanning rules file at: {rules_path}")

# 2. Define safe defaults for known network groups
address_defaults = {
    "HOME_NET":         "[192.168.1.0/24]",
    "EXTERNAL_NET":     "[8.8.8.8,1.1.1.1]",
    "HTTP_SERVERS":     "[192.168.1.10]",
    "DNS_SERVERS":      "[192.168.1.53]",
    "SMTP_SERVERS":     "[192.168.1.25]",
    "SQL_SERVERS":      "[192.168.1.143]",
    "SHELLCODE_SERVERS":"[192.168.1.200]",
    "SIP_SERVERS":      "[192.168.1.60]",
    "AIM_SERVERS":      "[192.168.1.99]",
}

# 3. Define safe defaults for known port groups
port_defaults = {
    "HTTP_PORTS":     "[80,443,8080,8000]",
    "DNS_PORTS":      "[53]",
    "SMTP_PORTS":     "[25,587]",
    "SQL_PORTS":      "[1433,3306]",
    "SHELLCODE_PORTS":"[10000]",
    "SIP_PORTS":      "[5060]",
    "AIM_PORTS":      "[4099]",
    "FTP_PORTS":      "[21]",
    "IRC_PORTS":      "[6667]",
    "TELNET_PORTS":   "[23]",
    "RDP_PORTS":      "[3389]"
}

# 4. Patterns for detection
net_pattern  = re.compile(r"\$(\w+(?:_NET|_SERVERS))\b")
port_pattern = re.compile(r"\$(\w+_PORTS)\b")

detected_nets  = set()
detected_ports = set()

# 5. Scan combined.rules
if os.path.exists(rules_path):
    with open(rules_path, "r") as f:
        for line in f:
            detected_nets.update(net_pattern.findall(line))
            detected_ports.update(port_pattern.findall(line))
else:
    print(f"❌ {rules_path} not found, skipping variable detection")

print(f"🔍 Detected network variables: {sorted(detected_nets)}")
print(f"🔍 Detected port variables:    {sorted(detected_ports)}")

# 6. Build config lines
lines = [
    "%YAML 1.1",
    "---",
    f"# Generated by gen_suricata_config.py at {datetime.utcnow().isoformat()}Z",
    "vars:",
    "  address-groups:"
]

# 6a. Populate address-groups
for var in sorted(detected_nets):
    val = address_defaults.get(var, "[0.0.0.0/0]")
    lines.append(f'    {var}: "{val}"')

# 6b. Populate port-groups
lines.append("")  # blank line for readability
lines.append("  port-groups:")
for var in sorted(detected_ports):
    val = port_defaults.get(var, "[1]")
    lines.append(f'    {var}: "{val}"')

# 7. Final stanzas
lines.append("")
lines.append("default-rule-path: rules")
lines.append("default-log-dir: /tmp/suricata-logs")
lines.append("")

# 8. Write out config to repo root
with open(output_path, "w") as out:
    out.write("\n".join(lines))

print(f"✔ Suricata config written to {output_path}")