#!/usr/bin/env python3
import os
import re
from datetime import datetime

# 1. Resolve paths
script_dir = os.path.dirname(os.path.abspath(__file__))
repo_root  = os.path.abspath(os.path.join(script_dir, ".."))
rules_path = os.path.join(repo_root, "rules", "combined.rules")
output_path = "/tmp/suricata.yaml"

# 2. Base address‐group defaults
address_defaults = {
    "HOME_NET":        "[192.168.1.0/24]",
    "EXTERNAL_NET":    "[8.8.8.8,1.1.1.1]",
    "HTTP_SERVERS":    "[192.168.1.10]",
    "DNS_SERVERS":     "[192.168.1.53]",
    "SMTP_SERVERS":    "[192.168.1.25]",
    "SQL_SERVERS":     "[192.168.1.143]",
    "SHELLCODE_SERVERS":"[192.168.1.200]",
    "SIP_SERVERS":     "[192.168.1.5060]",
    "AIM_SERVERS":     "[192.168.1.4099]"
}

# 3. Safe default port‐group mappings
port_defaults = {
    "HTTP_PORTS":     "[80,443,8080,8000]",
    "DNS_PORTS":      "[53]",
    "SMTP_PORTS":     "[25,587]",
    "SQL_PORTS":      "[1433,3306]",
    "SHELLCODE_PORTS":"[10000]",
    "SIP_PORTS":      "[5060]",
    "AIM_PORTS":      "[4099]",
    "FTP_PORTS":      "[21]",
    "IRC_PORTS":      "[6667]",
    "TELNET_PORTS":   "[23]",
    "RDP_PORTS":      "[3389]"
}

# 4. Scan combined.rules for any $*_PORTS
detected_ports = set()
port_pattern = re.compile(r"\$(\w+_PORTS)\b")

if os.path.exists(rules_path):
    with open(rules_path, "r") as f:
        for line in f:
            for var in port_pattern.findall(line):
                detected_ports.add(var)
else:
    print(f"❌ combined.rules not found at {rules_path}, skipping port var scan")

# 5. Print what we found
print(f"🔍 Detected port variables: {sorted(detected_ports)}")

# 6. Build the YAML lines
lines = [
    "%YAML 1.1",
    "---",
    f"# Generated by gen_suricata_config.py at {datetime.utcnow().isoformat()}Z",
    "vars:",
    "  address-groups:"
]
# 6a. Address‐group entries
for name, cidr in address_defaults.items():
    lines.append(f"    {name}: \"{cidr}\"")

# 6b. Port‐group entries
lines.append("")  # blank line for readability
lines.append("  port-groups:")
for port_var in sorted(detected_ports):
    val = port_defaults.get(port_var, "[1]")
    lines.append(f"    {port_var}: \"{val}\"")

# 7. Final stanzas
lines.append("")  # blank line
lines.append("default-rule-path: rules")
lines.append("default-log-dir: /tmp/suricata-logs")
lines.append("")  # ensure trailing newline

# 8. Write out config
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, "w") as out:
    out.write("\n".join(lines))

print(f"✔ Suricata config written to {output_path}")